# Generated by Django 4.2.8 on 2025-06-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_borrower_borrowrecord_category_librarian_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='address',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='date_hired',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='employee_id',
        ),
    ]
