# Generated by Django 4.2.8 on 2025-06-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_remove_librarian_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='username',
            field=models.CharField(default='Username', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
