# Generated by Django 4.2.8 on 2025-06-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_librarian_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='password',
            field=models.CharField(default='Password', max_length=128),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='username',
            field=models.CharField(default='Username', max_length=150, unique=True),
        ),
    ]
