# Generated by Django 4.2.8 on 2025-06-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_librarian_password_alter_librarian_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='password',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='username',
        ),
        migrations.AddField(
            model_name='librarian',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
