# Generated by Django 4.2.8 on 2025-06-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_remove_librarian_password_remove_librarian_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='employee_id',
        ),
    ]
