# Generated by Django 4.2.8 on 2025-06-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_remove_librarian_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
    ]
