# Generated by Django 4.2.8 on 2025-06-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateField(),
        ),
    ]
