# Generated by Django 4.2.8 on 2025-06-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_borrowrecord_actual_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
